AWSTemplateFormatVersion: '2010-09-09'
Description: "This template will deploy this job."

Resources:
  MessageLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: com.serverless.Handler
      FunctionName: qilin-metrics-feeder
      Role: arn:aws:iam::494526681395:role/for-aws-training-2
      Code:
        S3Bucket: qilin-metrics-feeder
        S3Key: qilin-metrics-feeder.jar
      Runtime: java8
      Timeout: 30
      MemorySize: 512